services:
  app:
    image: invoiceninja/invoiceninja-debian:5.13.43
    restart: unless-stopped
    environment:
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      REQUIRE_HTTPS: ${REQUIRE_HTTPS}
    
      CACHE_DRIVER: ${CACHE_DRIVER}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
    
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}
    
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    
      IN_USER_EMAIL: ${IN_USER_EMAIL}
      IN_PASSWORD: ${IN_PASSWORD}
    
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    
      PHANTOMJS_PDF_GENERATION: ${PHANTOMJS_PDF_GENERATION}
      PDF_GENERATOR: ${PDF_GENERATOR}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      
      IS_DOCKER: ${IS_DOCKER}
    volumes:
      - app_public:/var/www/html/public
      - app_storage:/var/www/html/storage

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      #- nginx:/etc/nginx/conf.d:ro
      - app_public:/var/www/html/public:ro
      - app_storage:/var/www/html/storage:ro

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  app_public:
  app_storage:
  mysql_data:
  redis_data:
